---

- name: Restart Supervisor Sentry
  supervisorctl:
    name: "{{ item }}"
    state: restarted
  with_items:
    - sentry-web
    - sentry-cron
    - sentry-worker

- name: Start Supervisor Sentry
  supervisorctl:
    name: "{{ item }}"
    state: started
  with_items:
    - sentry-web
    - sentry-cron
    - sentry-worker

- name: Supervisor started
  service:
    name: supervisor
    state: started
